name: build full release
on:
  workflow_dispatch:
  create:
    tags:
      - '*'

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - flavor: bullseye
            image: debian:bullseye
          - flavor: bookworm
            image: debian:bookworm
          - flavor: trixie
            image: debian:trixie
          - flavor: noble
            image: ubuntu:noble
    container:
      image: "${{ matrix.image }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare build environment
        run: ./scripts/ci/setup-build-env.sh
      - name: Run build script
        run: ./scripts/build.sh
      - name: Add flavor suffix to package filename
        run: |
          shopt -s nullglob
          for x in ./*.deb; do
            base="$(basename "$x")"
            pkg="${base%%_*}"
            tail="${base#${pkg}_}"
            version="${tail%_*}"
            arch="${tail##*_}"
            mv "$x" "./${pkg}_${version}~${{ matrix.flavor }}_${arch}"
          done
      - name: Upload deb files
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.flavor }}
          path: ./*.deb

  merge-artefacts:
    name: Merge all deb files to single artifact
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: debian-packages
        uses: actions/upload-artifact/merge@v4
        with:
          name: merged-artifacts
          pattern: packages-*

  add_release:
    name: Add package to release
    needs: merge-artefacts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: merged-artifacts
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./*.deb

  add_repo:
    name: Add packages to public debian repository
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: merge-artefacts
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: "merged-artifacts"
      - name: Add releases to repo
        uses: smeinecke/apt-repo-action@master
        with:
          github_token: ${{ github.token }}
          repo_supported_arch: |
            amd64
          repo_supported_version: |
            trixie
            bookworm
            bullseye
            noble
          file: |
            *.deb
          version_by_filename: true
          private_key: ${{ secrets.APT_SIGNING_KEY }}
          key_passphrase: ""
